gitpod-io/leeway

- cmd/build.go
- pkg/leeway/reporter.go
Adds a [werft](https://github.com/32leaves/werft) compatible reporter. Enable using `--werft`.
> [werft] Added werft compatible reporter

- pkg/leeway/build.go
Fixes situations where leeway tries to build Docker packages based on old images although newer ones have already been published.
`docker build --pull` does a `pull` on every image mentioned in the `Dockerfile`, which in turn checks and download newer versions if necessary.
> Docker builds: Try to `--pull` newer images on every build

- BUILD.yaml
- cmd/describe.go
- go.mod
- go.sum
- pkg/leeway/package.go
- pkg/leeway/scripts_test.go
- pkg/leeway/workspace.go
- pkg/leeway/workspace_test.go
- pkg/prettyprint/prettyprint.go
instead of the entire component's `BUILD.yaml`.
Fixes TypeFox/leeway#9
> Compute package hashes using the package's definition only,

- pkg/leeway/build.go
Thanks @meysholdt for your help in finding this bug in the first place.
Fixes TypeFox/leeway#18
> [typescript] Disable yarn cache when installing offline-mirror package

- cmd/describe.go
- pkg/leeway/build.go
- pkg/leeway/package.go
- pkg/leeway/workspace.go
- pkg/vet/docker.go
- pkg/vet/generic.go
- pkg/vet/packages.go
Prior to this change the build-time filesystem layout was created implicitly from the package names. This method breaks for nested workspaces where package names differ depending on their context.
This makes built-time layout explicit by introducing a "layout" section in the package description. If no explicit layout is set, leeway will fall back to its prior behaviour and use the dependency's filesystem safe name. This mechanism is implemented during linking s.t. the build-time layout stays stable across nested workspaces.
`leeway describe` has been updated accordingly to show the layout.
`leeway vet` finds layout path clashes if two dependencies occupy the same path at build-time.
> [layout] Make build-time filesystem layout explicit

- cmd/build.go
- pkg/leeway/build.go
This might serve as a first proposal for #31.
There are several things to discuss:
- does it makes sense to merge `cache` and `(additional) remote cache`?
- Does it make sense to have the `pull=` prefix to denote that it is a pull-only cache? I opted for that as it's the most compatible way in the future in both possible cases: 1. drop non-pull additional remote caches 2. add support for additional push-/pull+push-
- Names names names: `remote-cache`, `additional-remote-cache`? (Depends on choice 1)
> [remote-caches] Support multiple remote caches (pull-only for now)

- cmd/build.go
- pkg/leeway/build.go
which limits the number of parallel build steps leeway will execute. In practice this should help ease the CPU/IO and network load on the build machine.
Use the `-j` flag to set the number of max parallel tasks.
gitpod-io/gitpod is a good test repo for this.
> [build] Introduce concurrency limit

- cmd/export.go
- cmd/link.go
- go.mod
- go.sum
This PR makes link and export no longer experimental. I.e. one can run them without setting `LEEWAY_EXPERIMENTAL`
> [experimental] Make link and export non-experimental

- .gitpod.Dockerfile
- .gitpod.yml
- .vscode/settings.json
- README.md
- cmd/bashCompletion.go
- cmd/build.go
- cmd/collect.go
- cmd/describe-const.go
- cmd/describe-dependencies.go
- cmd/describe.go
- cmd/exec.go
- cmd/experiemental-unmount.go
- cmd/fmt.go
- cmd/init.go
- cmd/vet.go
- pkg/graphview/graphview.go
- pkg/leeway/build.go
- pkg/leeway/package.go
- pkg/leeway/reporter.go
- pkg/leeway/scripts.go
- pkg/leeway/watcher.go
- pkg/linker/golang.go
- pkg/vet/docker.go
This PR adds a linting stage to Go package builds. Beware: once this PR is merged, we'll try and lint all future Go builds.
By default we use golangci-lint, but this can be configured on a per-package level.
fixes #40
> [breaking] Add linting support

- cmd/describe.go
- pkg/leeway/build.go
- pkg/leeway/package.go
- pkg/leeway/workspace.go
to allow workspace-wide modification of package configurations.
For example:
```YAML
defaultVariant:
config:
go:
lintCommand: 
- "golangci-lint"
- "run"
- "--disable"
- "govet,typecheck"
```
> [workspace] Introduce a default variant

- pkg/leeway/build.go
When a `go generate` instruction is provided if the generation command create go code there's very high a chance that this code will be missing if `go get` relies on it and thus the build will fail.
This PR moves the generate command to be always done before the get command.
Signed-off-by: Lorenzo Fontana <lo@linux.com>
> [build] Execute go generate before go get tries to build the package

- README.md
- pkg/leeway/build.go
- pkg/leeway/package.go
Adds a new field to Docker package configuration which gets serialised back to YAML and becomes part of the package tarball in `metadata.yaml`. This provides a convenient way to attach metadata to Docker builds.
> [docker] Support metadata in Docker packages

- cmd/describe.go
- fixtures/pkgs/generic/BUILD.yaml
- pkg/leeway/build.go
- pkg/leeway/package.go
- pkg/vet/generic.go
Basis for discussion in #53 
This PR adds two things, actually:
- the `Test` field to generic packages, which has the same type as `Command`: `[][]string`
- the `DontTest` field, analogous to the other package types. This is not strictly required, but make sense as it allows to (temporarily) disable a package at dev time analogous to the other package types without commenting out the `test` section in the build.yaml.
> extends --dont-test to also cover "generic" packages

- cmd/build.go
- pkg/leeway/build.go
allows `leeway --docker-build-options=bridge=none`, for example.
Fixes #
```release-note
```
> add "docker-build-options" for passing options to "docker build"

- pkg/leeway/build.go
Use `go mod download` instead of `go get` to properly fail on incomplete `go.mod`/`go.sum` files.
> [go] Use go mod download instead of go get

- cmd/experiemental-unmount.go
- cmd/experimental-mount.go
- cmd/root.go
- pkg/leeway/cache.go
Add cache support for minio
used for self-hosted gitpod develop gitpod
Fixes #
1. need install minio cli
2. set login info
```bash
mc alias set minio http://IP:PORT/ user pass --api S3v4
```
3. set env var LEEWAY_REMOTE_CACHE_STORAGE=MINIO
4. set env var LEEWAY_REMOTE_CACHE_BUCKET=bucket
5. use leeway
```release-note
NONE
```
> Add support for minio

- README.md
- cmd/describe-gitinfo.go
- cmd/provenance-assert.go
- cmd/provenance-export.go
- cmd/provenance.go
- pkg/leeway/build.go
- pkg/leeway/package.go
- pkg/leeway/provenance.go
- pkg/leeway/workspace.go
- pkg/provutil/access.go
- pkg/provutil/assert.go
This PR builds on prior work which introduced SLSA provenance support to leeway. It adds 
- some debugging functionality and inspection CLI,
- improves memory efficiency during attestation bundle generation,
- increases the level of detail in the generated provenance
- fixes the Git status dirty flag (add adds `leeway describe git-info`)
> Improve provenance support

- README.md
- cmd/provenance-assert.go
- cmd/provenance-export.go
- cmd/provenance.go
- pkg/leeway/build.go
- pkg/leeway/provenance.go
- pkg/provutil/access.go
When building Docker images without pushing them to a registry, leeway will call `docker save` instead. In this case we still need to add the provenance bundle, and compute the subject list from the entries of tar file rather than a fileset.
This PR also enables the `leeway provenance` commands for attestation bundle files in addition to pulling them out of a package.
> Fix provenance generation issues with tar-file exported Docker builds

- .goreleaser.yml
The current leeway doesn't include the Darwin ARM64 release
N/A
I don't know how to trigger the gorelease to create a new release in my forked repository.
But I think adding this attribute to the gorelease.yml may work.
```release-note
Support Darwin ARM64.
```
N/A
> Build and release Darwin ARM64

- .goreleaser.yml
Reverts gitpod-io/leeway#84
Unfortunately this doesn't build:
```
• pipe skipped              error=not available for snapshots
• building binaries
• building                  binary=/workspace/leeway/dist/leeway_darwin_amd64/leeway
• building                  binary=/workspace/leeway/dist/leeway_linux_386/leeway
• building                  binary=/workspace/leeway/dist/leeway_linux_amd64/leeway
• building                  binary=/workspace/leeway/dist/leeway_linux_arm64/leeway
⨯ build failed after 24.46s error=failed to build for darwin_amd64: # github.com/opencontainers/runc/libcontainer/configs
../go/pkg/mod/github.com/opencontainers/runc@v1.1.1/libcontainer/configs/mount.go:34:11: undefined: unix.MountAttr
../go/pkg/mod/github.com/opencontainers/runc@v1.1.1/libcontainer/configs/mount.g …
```
> Revert "Build and release Darwin ARM64"

- pkg/leeway/build.go
Fix docker build regression introduced in https://github.com/gitpod-io/leeway/commit/eb116133f13ed4a9cc3cfd03b94a3733d5d03be8
> Fix docker build regression

- pkg/leeway/build.go
Removes the `_tests` binaries from Go packages.
This is a non-backwards compatible change that might break builds.
> [go] Stop building test binaries

- BUILD.yaml
- cmd/build.go
- cmd/exec.go
- cmd/experiemental-unmount.go
- cmd/experimental-mount.go
- cmd/init.go
- cmd/plumbing-exec.go
- go.mod
- go.sum
- pkg/gokart/analyzers.go
- pkg/graphview/graphview.go
- pkg/leeway/build.go
- pkg/leeway/scripts.go
- pkg/leeway/watcher.go
- pkg/leeway/workspace.go
- pkg/leeway/workspace_test.go
- pkg/linker/golang.go
- pkg/linker/yarn.go
- pkg/vet/components.go
- pkg/vet/docker_test.go
- pkg/vet/yarn.go
- remove `go.rice` and replace it with Go native embedding
- debounce `--watch` so to make it less noisy and actually usable
- remove use of `ioutil`
> Misc maintainance stuff

- pkg/leeway/provenance.go
Skip hash of directories
Fixes https://github.com/gitpod-io/leeway/issues/112
```release-note
NONE
```
> Refactor inTotoMaterials to skip directories

- pkg/leeway/cache.go
quick patch to solve the gsutil permission issue. We should use the client library to talk to GCS, as it will give us a better experience.
Your implementation [here](https://github.com/gitpod-io/leeway/blob/322c71ed69826a9f6da4bcf27e78934c4dfc7ec8/pkg/leeway/cache.go#L125-L136) was handling this @mads-hartmann , I broke it 🙈 
Fixes #
```release-note
NONE
```
> Patch gsutil 401 if not logged in

- pkg/leeway/build.go
Consider the case where you have three Leeway Go packages A, B, C where A depends on B. B depends on C and C is ephemeral.
The ephemeral package C will always be built whenever B is built as it is never cached.
That means, if B doesn't need to be rebuilt, then C won't be built either.
As it is ephemeral it won't be in the cache either, which means that if you try to build package A when B is cached, then the build will fail as C isn't in the cache.
This PR fixes it so that ephemeral packages are ignored when checking the transitive dependencies of Go packages.
This was already the case for Yarn packages - the implementation (and comments) have been copied over verbatim
For more context around ephemeral packages see this [internal Notion meeting …
> Go: Ignore ephemeral packages when checking transitive dependencies

- cmd/exec.go
- pkg/leeway/build.go
- pkg/leeway/format.go
- pkg/leeway/package.go
- pkg/leeway/workspace.go
- pkg/vet/yarn.go
Removes the long deprecated typescript package type.
Fixes #123
```release-note
[breaking] Remove deprecated `typescript` package type
```
> Remove deprecated Typescript package type

- pkg/leeway/build.go
Logs `go mod download` only when in verbose (debug) mode
Fixes #107
- `leeway build -v`
- `leeway build`
```release-note
Log "go mod download" output only when in verbose mode
```
> [go] Log go mod download only when verbose

- pkg/vet/components.go
- pkg/vet/docker_test.go
- pkg/vet/vet.go
- pkg/vet/yarn.go
Add vet for node_module source inclusion and fix two minor issues around vet:
- better details when a vet check fails
- support build `BUILD.js` for the `fmt` vet
Fixes #126
Run `leeway vet` on a package which includes `node_modules`
```release-note
[vet] Minor bug fixes
[vet] New check for Yarn packages which include `node_modules/` in their sources
```
> Add vet for node_module source inclusion

- pkg/leeway/build.go
- pkg/leeway/build_test.go
- pkg/leeway/package_test.go
- pkg/leeway/scripts_test.go
- pkg/testutil/testutil.go
- pkg/testutil/testutil_test.go
This change allows the reuse of previously built Docker images in subsequent packages, e.g.
comp/BUILD.yaml:
```
packages:
- name: pkg0
type: docker
config:
dockerfile: pkg0.Dockerfile
image: 
- "foobar:latest"
- name: pkg1
type: docker
deps:
- :pkg0
config:
Dockerfile: pkg1.Dockerfile
```
comp/pkg1.Dockerfile
```
FROM ${DEP_COMP__PKG0}
RUN echo using prior image as base
```
We want to use this in dedicated to build a base image for functions, and refer to it in subsequent packages.
See test in this PR
> [docker] Support daisy-chaining Docker packages

- README.md
- pkg/leeway/build.go
- pkg/leeway/package.go
- pkg/leeway/workspace.go
This change allows leeway to build "muti-main" Go projects. Before this change one would have to produce multiple packages at the root of a Go module. With this change we can have multiple leeway components within the same Go module. 
```
foobar
├── go.mod
├── go.sum
└── cmd
├── hello
│   ├── main.go
│   └── BUILD.yaml
└── world
├── main.go
└── BUILD.yaml
```
Where the `BUILD.yaml` looks like this:
```yaml
packages:
- name: app
type: go
srcs:
- main.go
config:
goMod: ../go.mod
```
```
foobar
├── go.mod
├── go.sum
├── BUILD.yaml
└── cmd
├── hello
│   ├── main.go
└── world
├── main.go
```
Where the `BUILD.yaml` looks like this:
```yaml
packages:
- name: hello
type: go
srcs:
- go.mod
- go.sum
- hello/*.go
prepare:
- ["mv", "hello/main.go", "."]
- name: world
type: go
srcs:
- go.mod
- go.sum …
```
> [go] Support "nested" Go main builds

- README.md
- pkg/leeway/workspace.go
- pkg/leeway/workspace_test.go
- pkg/testutil/testutil.go
This PR adds support for a new `WORKSPACE.args.yaml` which carries default argument overrides. This is useful to adapt a local workspace without committing values to Git.
See unit test.
> Add support for local default arg overrides

- pkg/leeway/reporter.go
Add docker image results to the HTML report
This also changes the structure of the report so that it starts with a `<table>` that provides a quick overview of the packages that were built. Each row also contains a link to further down in the report as each package now has a separate `<h2>` section with details about the package. This makes it easier to add more details as we go without loosing the nice concise overview
Part of https://github.com/gitpod-io/gitpod/issues/15485
I tested this in gitpod-io/gitpod. Here's the screenshot.
```release-note
HTML report has been improved and extended to include results for any docker images that were built
```
N/A
> Add docker image results to the HTML report

- .github/workflows/release.yaml
[GoReleaser is failing](https://github.com/gitpod-io/leeway/actions/runs/3828388013). with `failed to build for windows_amd64_v1: exit status 2` and `2023-01-03T09:46:38.4942225Z ##[error]../../../go/pkg/mod/github.com/opencontainers/runc@v1.1.4/libcontainer/devices/device.go:173:9: undefined: mkDev`
We're using "latest" which is currently v1.14.1 - it is only 18 hours old. Maybe is contains a regressions. The [last succesful release](https://github.com/gitpod-io/leeway/actions/runs/3684651081/jobs/6234636719) was using v1.13.1 so lets give that a try.
No issue.
Merge into main and re-run the job.
```release-note
NONE
```
N/A
> Use v1.13.1 as that was the version used in the last successful release

- cmd/collect.go
This adds shell completions for `cmd/collect` and adds argument validation.
Fixes #
```bash
gitpod /workspace/leeway (alt/collect-completions-validations) $ ./leeway collect <TAB> <TAB>
components  files       packages    scripts     
gitpod /workspace/leeway (alt/collect-completions-validations) $ ./leeway collect
```
```bash
gitpod /workspace/leeway (alt/collect-completions-validations) $ ./leeway collect flies
Error: invalid argument "flies" for "leeway collect"
```
```release-note
[cmd] Validate collect args, add collect arg completion
```
> [cmd] add completions for collect, validate collect args

- pkg/leeway/build.go
Reopening https://github.com/gitpod-io/leeway/pull/153 to fix script dependencies not being cached
Fixes #
/hold
> Only use buildContext when building packages

- pkg/leeway/workspace.go
Prior to this change the following component would not build without passing `foobar` as build arg:
```YAML
const:
- foobar=baz
packages:
- name: demo
type: generic
argdeps:
- foobar
```
> Allow const as argdep

- pkg/leeway/build.go
- pkg/leeway/build_darwin.go
- pkg/leeway/build_linux.go
I.e. produces the following when running on mac without GNU compatible cp:
```
FATA[0000] leeway requires a GNU-compatible cp. Please install using `brew install coreutils`; make sure you update your path after installing.
```
> Fail helpfully when running on mac

- cmd/exec.go
- pkg/leeway/package.go
to make `leeway exec --cache-key foo --components -- ls` work
> Support cached execution for components

- pkg/leeway/build.go
- pkg/leeway/build_internal_test.go
- pkg/leeway/reporter.go
This PR adds test coverage reporting for Go packages. Coverage is reported by the console and segment reporter.
> Report coverage as package reporter

- .devcontainer/devcontainer.json
- cmd/root.go
- pkg/leeway/workspace.go
This PR makes leeway automatically discover the workspace route by traveling up the path all the way to the root of the file system and looking for a WORKSPACE.yaml file.
> Discover workspace root

- cmd/build.go
- pkg/leeway/reporter.go
so that subsequent steps can perform operations based on the build
> Add GitHub action build reporter

- pkg/leeway/build.go
This PR makes LEEWAY_WORKSPACE_ROOT available for commands executed during build. This way one can refer to e.g. config files in lint or test commands.
It also fixes a regression for test coverage collection which would affect Go packages referencing other go dependencies, when using Go workspaces.
> Go build fixes

- pkg/leeway/build.go
Do not run logs with `-v` flag by default.
> Run go test -v only if -v flag is set

- pkg/leeway/provenance.go
fixes ["Token Too Long"](https://github.com/gitpod-io/gitpod-next/actions/runs/9230864853/job/25399829050?pr=1658#step:12:9417) found in CI
> Replace AddFromBundle bufio Scanner with Reader

- go.mod
- go.sum
to avoid issues such as 
```
[api/go:lib] build started (version 5bce824fdb96543d9a23000e405c27e0000d4661)
[api/go:lib] package build failed while preping
[api/go:lib] Reason: cannot read go.work file: go.work:3: unknown directive: toolchain
```
> Bump modfile to add toolchain support

- .github/workflows/release.yaml
- .goreleaser.yml
Fixes #
>  ⨯ release failed after 1m51s               error=failed to build for linux_386: exit status 1: # github.com/opencontainers/runc/libcontainer/specconv
> Error: ../../../go/pkg/mod/github.com/opencontainers/runc@v1.2.0/libcontainer/specconv/spec_linux.go:1015:33: undefined: userns.GetUserNamespaceMappings
> Error: ../../../go/pkg/mod/github.com/opencontainers/runc@v1.2.0/libcontainer/specconv/spec_linux.go:1031:15: undefined: userns.IsSameMapping
> Error: ../../../go/pkg/mod/github.com/opencontainers/runc@v1.2.0/libcontainer/specconv/spec_linux.go:1032:13: undefined: userns.IsSameMapping
> Update goreleaser and remove i386

- .github/workflows/release.yaml
- .gitignore
- .goreleaser.yaml
- go.mod
- go.sum
- Rollback github.com/opencontainers/runc to v1.1.10 (any version after that throws compilation errors).
- Ensure goreleaser build works.
```
❯ GITHUB_TOKEN=0 /usr/local/bin/goreleaser --verbose release --clean --config .goreleaser.yaml --snapshot
• verbose output enabled
• using configuration                              path=.goreleaser.yaml
• parallelism: 12
• skipping announce, publish and validate...
• cleaning distribution directory
• loading environment variables
• using token from  $GITHUB_TOKEN
• token type: github
• getting and validating git state
• git command result                             args=[-c log.showSignature=false rev-parse --is-inside-work-tree] stdout=true stderr=
• git command result                             args=[-c log.showSignature=false rev-parse …
```
> Update goreleaser configuration

- pkg/leeway/build.go
- pkg/leeway/version.go
- pkg/leeway/workspace.go
Fixes build failure if the dependency of a cached package (no longer) exists in the cache. Now, also checks and builds if needed the dependencies of packages that are already built (in cache).
Drive-by fixes:
- `unkown` -> `unknown`
- ignore empty lines in `.leewayignore`. An empty line would otherwise match every file path and ignore everything
Fixes https://gitpod.slack.com/archives/C06C23ZTFL6/p1733906120191529
/hold
> Build dependencies of cached packages

- cmd/build.go
- pkg/leeway/build.go
- pkg/leeway/cache/local/fs.go
- pkg/leeway/cache/remote/s3.go
- pkg/leeway/cache/remote/s3_download_test.go
- pkg/leeway/cache/remote/s3_test.go
- pkg/leeway/scripts.go
In leeway, some tasks of a generic or docker type do not download the generated assets during the build. This means they will not exist in the local cache and will be built on every build run. This results in unnecessary build time for specific CI jobs and bypasses the use of the cache.
```
🌎  cached remotely (ignored)     runner/linux:raw-app                           (version 18f83f9e73331afe67b8f8eb10e5bc5570aa62c7)
🌎  cached remotely (ignored)     runner/shared/openssh:docker                   (version 8e42cdd4b76079dafce8eb748bda6543c7a3273a)
🌎  cached remotely (ignored)     runner/shared/openssh:runner                   (version 5b4728c43b439b641fe3fc167488cd842a435131)
📥  cached remotely (downloaded)  dev/oidc:lib                                   (version …
```
> Improve build cache asset handling
